import { Config } from '@stencil/core';

import { reactOutputTarget as react } from '@stencil/react-output-target';

export const config: Config = {
  namespace: 'primitive-comp',
  outputTargets: [
    react({
      // name of the Stencil Component Library
      componentCorePackage: 'primitive-comp',
      // This file gets generated by React wrapper function and contains definitions of all Wrapper components
      proxiesFile: '../primitive-comp-react/src/components/stencil-generated/index.ts',
      includeDefineCustomElements: true,
    }),
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
